<?php
/**
 * Implements hook_theme().
 */
function openy_prgf_session_table_theme() {
  return [
    'node__session__session_table_row' => [
      'base hook' => 'paragraph',
    ],
  ];
}
/**
 * Implements hook_preprocess_HOOK().
 */
function openy_prgf_session_table_preprocess_node(&$vars) {
  if ($vars['view_mode'] == 'session_table_row') {
    $vars['theme_hook_suggestions'][] = 'node__session__session_table_row';
  }
}
